using utilidadesv2.Entidades;

namespace utilidadesv2.Servicios
{
    public class ServicioDeClabes
    {
        private string GenerarClabe(string depositoId, string plaza)
        {
            string banco = "659"; // Opciones empresariales del norte            
            string pad = "00000000000";

            depositoId = (pad + depositoId).Substring(depositoId.Length);
            string clabe = banco + plaza + depositoId;

            int[] factorDePeso = { 3, 7, 1, 3, 7, 1, 3, 7, 1, 3, 7, 1, 3, 7, 1, 3, 7 };
            int[] producto = new int[clabe.Length];

            for (int i = 0; i < clabe.Length; i++)
            {
                producto[i] = int.Parse(clabe[i].ToString()) * factorDePeso[i];
                producto[i] = producto[i] % 10;
            }

            int suma = 0;
            for (int i = 0; i < producto.Length; i++)
            {
                suma += producto[i];
            }

            suma = suma % 10;
            int digitoVerificador = (10 - suma) % 10;
            clabe = clabe + digitoVerificador.ToString();

            return clabe;
        }

        public string GenerarClabe(string depositoId)
        {
            Plaza plaza;
            string plazaString;
            string clabe;

            plaza = ObtenerPlaza();
            plazaString = plaza.Id < 100 ? "0" + plaza.Id : plaza.Id.ToString();
            if (string.IsNullOrEmpty(depositoId))
                depositoId = ObtenerDepositoId();
            clabe = GenerarClabe(depositoId, plazaString);

            return clabe;
        }

        private string ObtenerDepositoId()
        {
            string depositoId;
            Random random = new Random();

            depositoId = random.Next(1, 9).ToString() + random.Next(0, 9) + random.Next(0, 9) + random.Next(0, 9) + random.Next(0, 9);

            return depositoId;
        }

        private Plaza ObtenerPlaza()
        {
            List<Plaza> plazas;
            Plaza plaza;
            Random rand = new Random();

            plazas = ObtenerPlazas();
            plaza = plazas[rand.Next(0, (plazas.Count - 1))];

            return plaza;
        }

        private List<Plaza> ObtenerPlazas()
        {
            List<Plaza> plazas;

            plazas = new List<Plaza>
            {
         new Plaza { Id=10,Nombre="Aguascalientes"},
         new Plaza { Id=12,Nombre="Calvillo"},
         new Plaza { Id=14,Nombre="Jesus Maria"},
         new Plaza { Id=20,Nombre="Mexicali"},
         new Plaza { Id=22,Nombre="Ensenada"},
         new Plaza { Id=27,Nombre="Tecate"},
         new Plaza { Id=27,Nombre="Tijuana"},
         new Plaza { Id=28,Nombre="La Mesa"},
         new Plaza { Id=28,Nombre="Rosarito"},
         new Plaza { Id=28,Nombre="Tijuana"},
         new Plaza { Id=40,Nombre="La Paz"},
         new Plaza { Id=41,Nombre="Cabo San Lucas"},
         new Plaza { Id=42,Nombre="Ciudad Constitucion"},
         new Plaza { Id=43,Nombre="Gerrero Negro"},
         new Plaza { Id=45,Nombre="San Jose Del Cabo"},
         new Plaza { Id=46,Nombre="Santa Rosalia"},
         new Plaza { Id=50,Nombre="Campeche"},
         new Plaza { Id=51,Nombre="Calkini"},
         new Plaza { Id=52,Nombre="Ciudad Del Carmen"},
         new Plaza { Id=53,Nombre="Champoton"},
         new Plaza { Id=60,Nombre="Gomez Palacio"},
         new Plaza { Id=60,Nombre="Torreon"},
         new Plaza { Id=62,Nombre="Ciudad Acu?A"},
         new Plaza { Id=68,Nombre="Monclova"},
         new Plaza { Id=71,Nombre="Nava"},
         new Plaza { Id=72,Nombre="Nueva Rosita"},
         new Plaza { Id=74,Nombre="Parras De La Fuente"},
         new Plaza { Id=75,Nombre="Piedras Negras"},
         new Plaza { Id=76,Nombre="Ramos Arizpe"},
         new Plaza { Id=77,Nombre="Sabinas"},
         new Plaza { Id=78,Nombre="Saltillo"},
         new Plaza { Id=80,Nombre="San Pedro De Las Colonias"},
         new Plaza { Id=90,Nombre="Colima"},
         new Plaza { Id=95,Nombre="Manzanillo"},
         new Plaza { Id=97,Nombre="Tecoman"},
         new Plaza {Id=100,Nombre="Teran"},
         new Plaza {Id=100,Nombre="Tuxtla Gutierrez"},
         new Plaza {Id=103,Nombre="Arriaga"},
         new Plaza {Id=107,Nombre="Cintalapa"},
         new Plaza {Id=109,Nombre="Comitan"},
         new Plaza {Id=109,Nombre="Villa Las Rosas"},
         new Plaza {Id=111,Nombre="Chiapa De Corso"},
         new Plaza {Id=113,Nombre="F. Comalapa"},
         new Plaza {Id=114,Nombre="Huixtla"},
         new Plaza {Id=123,Nombre="Ocosingo"},
         new Plaza {Id=124,Nombre="Ocozocuautla"},
         new Plaza {Id=125,Nombre="Palenque"},
         new Plaza {Id=126,Nombre="Pichucalco"},
         new Plaza {Id=127,Nombre="Pijijiapan"},
         new Plaza {Id=128,Nombre="Reforma"},
         new Plaza {Id=130,Nombre="San Cristobal Las Casas"},
         new Plaza {Id=131,Nombre="Simojovel"},
         new Plaza {Id=133,Nombre="Tapachula"},
         new Plaza {Id=135,Nombre="Tonala"},
         new Plaza {Id=137,Nombre="Venustiano Carranza"},
         new Plaza {Id=138,Nombre="Villa Flores"},
         new Plaza {Id=140,Nombre="Yajalon"},
         new Plaza {Id=150,Nombre="Chihuahua"},
         new Plaza {Id=150,Nombre="Ciudad Delicias"},
         new Plaza {Id=152,Nombre="Ciudad Anahuac"},
         new Plaza {Id=155,Nombre="Ciudad Camargo"},
         new Plaza {Id=158,Nombre="Ciudad Cuauhtemoc"},
         new Plaza {Id=161,Nombre="Ciudad Guerrero"},
         new Plaza {Id=162,Nombre="Parral"},
         new Plaza {Id=163,Nombre="Ciudad Jimenez"},
         new Plaza {Id=164,Nombre="Ciudad Juarez"},
         new Plaza {Id=165,Nombre="Ciudad Madera"},
         new Plaza {Id=167,Nombre="El Molino De Namiquipa"},
         new Plaza {Id=168,Nombre="Nuevo Casas Grandes"},
         new Plaza {Id=180,Nombre="Atizapan"},
         new Plaza {Id=180,Nombre="Chalco"},
         new Plaza {Id=180,Nombre="Ciudad De Mexico"},
         new Plaza {Id=180,Nombre="Coacalco"},
         new Plaza {Id=180,Nombre="Cuautitlan"},
         new Plaza {Id=180,Nombre="Cuautitlan Izcalli"},
         new Plaza {Id=180,Nombre="Ecatepec"},
         new Plaza {Id=180,Nombre="Huehuetoca"},
         new Plaza {Id=180,Nombre="Huixquilucan"},
         new Plaza {Id=180,Nombre="Ixtapaluca"},
         new Plaza {Id=180,Nombre="Los Reyes La Paz"},
         new Plaza {Id=180,Nombre="Naucalpan"},
         new Plaza {Id=180,Nombre="Nezahualcoyotl"},
         new Plaza {Id=180,Nombre="Tecamac"},
         new Plaza {Id=180,Nombre="Teotihuacan"},
         new Plaza {Id=180,Nombre="Texcoco"},
         new Plaza {Id=180,Nombre="Tlalnepantla"},
         new Plaza {Id=190,Nombre="Durango"},
         new Plaza {Id=201,Nombre="Tepehuanes"},
         new Plaza {Id=202,Nombre="Vicente Guerrero"},
         new Plaza {Id=210,Nombre="Guanajuato"},
         new Plaza {Id=211,Nombre="Abasolo"},
         new Plaza {Id=212,Nombre="Acambaro"},
         new Plaza {Id=213,Nombre="Apaseo El Alto"},
         new Plaza {Id=214,Nombre="Apaseo El Grande"},
         new Plaza {Id=215,Nombre="Celaya"},
         new Plaza {Id=216,Nombre="Comonfort"},
         new Plaza {Id=217,Nombre="Coroneo"},
         new Plaza {Id=218,Nombre="Cortazar"},
         new Plaza {Id=219,Nombre="Cueramaro"},
         new Plaza {Id=220,Nombre="Dolores Hidalgo"},
         new Plaza {Id=222,Nombre="Irapuato"},
         new Plaza {Id=223,Nombre="Jaral Del Progreso"},
         new Plaza {Id=224,Nombre="Jerecuaro"},
         new Plaza {Id=225,Nombre="Leon"},
         new Plaza {Id=226,Nombre="Cd. Manuel Doblado"},
         new Plaza {Id=227,Nombre="Moroleon"},
         new Plaza {Id=229,Nombre="Penjamo"},
         new Plaza {Id=232,Nombre="Romita"},
         new Plaza {Id=233,Nombre="Salamanca"},
         new Plaza {Id=234,Nombre="Salvatierra"},
         new Plaza {Id=236,Nombre="San Felipe"},
         new Plaza {Id=237,Nombre="Purisima De Bustos"},
         new Plaza {Id=237,Nombre="San Francisco Del Rincon"},
         new Plaza {Id=238,Nombre="San Jose Iturbide"},
         new Plaza {Id=239,Nombre="San Luis De La Paz"},
         new Plaza {Id=240,Nombre="San Miguel Allende"},
         new Plaza {Id=244,Nombre="Silao"},
         new Plaza {Id=247,Nombre="Uriangato"},
         new Plaza {Id=248,Nombre="Valle De Santiago"},
         new Plaza {Id=249,Nombre="Yuriria"},
         new Plaza {Id=260,Nombre="Chilpancingo"},
         new Plaza {Id=261,Nombre="Acapulco"},
         new Plaza {Id=263,Nombre="Arcelia"},
         new Plaza {Id=264,Nombre="Atoyac De Alvarez"},
         new Plaza {Id=266,Nombre="Ciudad Altamirano"},
         new Plaza {Id=267,Nombre="Coyuca De Benitez"},
         new Plaza {Id=270,Nombre="Chilapa"},
         new Plaza {Id=271,Nombre="Huitzuco"},
         new Plaza {Id=272,Nombre="Iguala"},
         new Plaza {Id=272,Nombre="La Sabana"},
         new Plaza {Id=274,Nombre="Cuajinicuilapa"},
         new Plaza {Id=274,Nombre="Ometepec"},
         new Plaza {Id=275,Nombre="San Marcos"},
         new Plaza {Id=276,Nombre="Taxco"},
         new Plaza {Id=278,Nombre="Teloloapan"},
         new Plaza {Id=281,Nombre="Tlapa"},
         new Plaza {Id=282,Nombre="Ixtapa Zihuatanejo"},
         new Plaza {Id=282,Nombre="Zihuatanejo"},
         new Plaza {Id=290,Nombre="Pachuca"},
         new Plaza {Id=291,Nombre="Actopan"},
         new Plaza {Id=292,Nombre="Apam"},
         new Plaza {Id=293,Nombre="Atotonilco El Grande"},
         new Plaza {Id=294,Nombre="Ciudad Sahagun"},
         new Plaza {Id=294,Nombre="Teocaltiche"},
         new Plaza {Id=295,Nombre="Cuautepec"},
         new Plaza {Id=296,Nombre="Huejutla"},
         new Plaza {Id=297,Nombre="Huichapan"},
         new Plaza {Id=298,Nombre="Ixmiquilpan"},
         new Plaza {Id=303,Nombre="Progreso De Obregon"},
         new Plaza {Id=305,Nombre="Tepeapulco"},
         new Plaza {Id=308,Nombre="Tizayuca"},
         new Plaza {Id=311,Nombre="Tula De Allende"},
         new Plaza {Id=312,Nombre="Tulancingo"},
         new Plaza {Id=313,Nombre="Zacualtipan"},
         new Plaza {Id=314,Nombre="Zimapan"},
         new Plaza {Id=320,Nombre="El Salto"},
         new Plaza {Id=320,Nombre="Guadalajara"},
         new Plaza {Id=320,Nombre="San Pedro Tlaquepaque"},
         new Plaza {Id=320,Nombre="Tlajomulco"},
         new Plaza {Id=320,Nombre="Tonala"},
         new Plaza {Id=320,Nombre="Zapopan"},
         new Plaza {Id=326,Nombre="Ameca"},
         new Plaza {Id=327,Nombre="Arandas"},
         new Plaza {Id=330,Nombre="Atotonilco El Alto"},
         new Plaza {Id=331,Nombre="Atequiza"},
         new Plaza {Id=333,Nombre="Autlan"},
         new Plaza {Id=340,Nombre="Casimiro Castillo"},
         new Plaza {Id=341,Nombre="Cihuatlan"},
         new Plaza {Id=342,Nombre="Ciudad Guzman"},
         new Plaza {Id=346,Nombre="Chapala"},
         new Plaza {Id=348,Nombre="El Grullo"},
         new Plaza {Id=355,Nombre="Ixtlahuacan Del Rio"},
         new Plaza {Id=356,Nombre="Jalostotitlan"},
         new Plaza {Id=357,Nombre="Jamay"},
         new Plaza {Id=361,Nombre="La Barca"},
         new Plaza {Id=362,Nombre="Lagos De Moreno"},
         new Plaza {Id=370,Nombre="Ocotlan"},
         new Plaza {Id=373,Nombre="Pihuamo"},
         new Plaza {Id=375,Nombre="Las Juntas"},
         new Plaza {Id=375,Nombre="Nuevo Vallarta"},
         new Plaza {Id=375,Nombre="Pitillal"},
         new Plaza {Id=375,Nombre="Puerto Vallarta"},
         new Plaza {Id=381,Nombre="San Juan De Los Lagos"},
         new Plaza {Id=384,Nombre="San Miguel El Alto"},
         new Plaza {Id=385,Nombre="San Patricio Melaque"},
         new Plaza {Id=386,Nombre="Sayula"},
         new Plaza {Id=387,Nombre="Tala"},
         new Plaza {Id=389,Nombre="Tamazula De Gordiano"},
         new Plaza {Id=391,Nombre="Tecalitlan"},
         new Plaza {Id=396,Nombre="Tepatitlan"},
         new Plaza {Id=397,Nombre="Tequila"},
         new Plaza {Id=403,Nombre="Tototlan"},
         new Plaza {Id=404,Nombre="Tuxpam"},
         new Plaza {Id=411,Nombre="Villa Hidalgo"},
         new Plaza {Id=413,Nombre="Zacoalco De Torres"},
         new Plaza {Id=414,Nombre="Zapotiltic"},
         new Plaza {Id=416,Nombre="Zapotlanejo"},
         new Plaza {Id=420,Nombre="Toluca"},
         new Plaza {Id=421,Nombre="Acambay"},
         new Plaza {Id=422,Nombre="Almoloya De Juarez"},
         new Plaza {Id=424,Nombre="No Especificada"},
         new Plaza {Id=425,Nombre="Apaxco"},
         new Plaza {Id=426,Nombre="Atlacomulco"},
         new Plaza {Id=428,Nombre="Coatepec De Harinas"},
         new Plaza {Id=430,Nombre="Chicoloapan"},
         new Plaza {Id=431,Nombre="Chiconcuac"},
         new Plaza {Id=432,Nombre="El Oro"},
         new Plaza {Id=433,Nombre="Ixtapan De La Sal"},
         new Plaza {Id=434,Nombre="Ixtlahuaca"},
         new Plaza {Id=435,Nombre="Jilotepec"},
         new Plaza {Id=438,Nombre="Lerma"},
         new Plaza {Id=441,Nombre="Metepec"},
         new Plaza {Id=443,Nombre="Otumba"},
         new Plaza {Id=445,Nombre="San Mateo Atenco"},
         new Plaza {Id=446,Nombre="Tejupilco"},
         new Plaza {Id=448,Nombre="Temascaltepec"},
         new Plaza {Id=449,Nombre="Temoaya"},
         new Plaza {Id=450,Nombre="Tenancingo"},
         new Plaza {Id=451,Nombre="Tenago Del Valle"},
         new Plaza {Id=453,Nombre="Santiago Tiangistenco"},
         new Plaza {Id=455,Nombre="Tultepec"},
         new Plaza {Id=456,Nombre="Tultitlan"},
         new Plaza {Id=457,Nombre="Valle De Bravo"},
         new Plaza {Id=460,Nombre="Villa Nicolas Romero"},
         new Plaza {Id=463,Nombre="Zumpango"},
         new Plaza {Id=470,Nombre="Morelia"},
         new Plaza {Id=472,Nombre="Aguililla"},
         new Plaza {Id=476,Nombre="Apatzingan"},
         new Plaza {Id=480,Nombre="Cuidad Hidalgo"},
         new Plaza {Id=483,Nombre="Cotija"},
         new Plaza {Id=484,Nombre="Cuitzeo"},
         new Plaza {Id=492,Nombre="Huetamo"},
         new Plaza {Id=493,Nombre="Jacona"},
         new Plaza {Id=494,Nombre="Jiquilpan"},
         new Plaza {Id=496,Nombre="La Piedad"},
         new Plaza {Id=497,Nombre="Lazaro Cardenas"},
         new Plaza {Id=498,Nombre="Los Reyes"},
         new Plaza {Id=499,Nombre="Maravatio"},
         new Plaza {Id=501,Nombre="Nueva Italia"},
         new Plaza {Id=506,Nombre="Patzcuaro"},
         new Plaza {Id=508,Nombre="Purepero"},
         new Plaza {Id=509,Nombre="Puruandiro"},
         new Plaza {Id=512,Nombre="Sahuayo"},
         new Plaza {Id=515,Nombre="Tacambaro"},
         new Plaza {Id=517,Nombre="Tangancicuaro"},
         new Plaza {Id=519,Nombre="Tepalcatepec"},
         new Plaza {Id=523,Nombre="Tlazazalca"},
         new Plaza {Id=528,Nombre="Uruapan"},
         new Plaza {Id=533,Nombre="Yurecuaro"},
         new Plaza {Id=534,Nombre="Zacapu"},
         new Plaza {Id=535,Nombre="Zamora"},
         new Plaza {Id=536,Nombre="Zinapecuaro"},
         new Plaza {Id=537,Nombre="Zitacuaro"},
         new Plaza {Id=540,Nombre="Cuernavaca"},
         new Plaza {Id=542,Nombre="Cuautla"},
         new Plaza {Id=542,Nombre="Oaxtepec, Morelos"},
         new Plaza {Id=543,Nombre="Jiutepec"},
         new Plaza {Id=544,Nombre="Jojutla"},
         new Plaza {Id=545,Nombre="Puente De Ixtla"},
         new Plaza {Id=546,Nombre="Temixco"},
         new Plaza {Id=548,Nombre="Tetecala"},
         new Plaza {Id=549,Nombre="Yautepec"},
         new Plaza {Id=552,Nombre="Zacatepec"},
         new Plaza {Id=560,Nombre="Tepic"},
         new Plaza {Id=561,Nombre="Acaponeta"},
         new Plaza {Id=562,Nombre="Ahuacatlan"},
         new Plaza {Id=564,Nombre="Compostela"},
         new Plaza {Id=566,Nombre="Ixtlan Del Rio"},
         new Plaza {Id=571,Nombre="San Blas"},
         new Plaza {Id=573,Nombre="Santiago Ixcuintla"},
         new Plaza {Id=575,Nombre="Tuxpam"},
         new Plaza {Id=580,Nombre="Apodaca"},
         new Plaza {Id=580,Nombre="Cadereyta"},
         new Plaza {Id=580,Nombre="Cd. Guadalupe"},
         new Plaza {Id=580,Nombre="General Escobedo"},
         new Plaza {Id=580,Nombre="Monterrey"},
         new Plaza {Id=580,Nombre="San Nicolas De Los Garza"},
         new Plaza {Id=580,Nombre="San Pedro Garza Garcia"},
         new Plaza {Id=580,Nombre="Santa Catarina"},
         new Plaza {Id=583,Nombre="Allende"},
         new Plaza {Id=592,Nombre="General Zuazua"},
         new Plaza {Id=595,Nombre="Linares"},
         new Plaza {Id=597,Nombre="Montemorelos"},
         new Plaza {Id=599,Nombre="Sabinas Hidalgo"},
         new Plaza {Id=600,Nombre="Salinas Victoria"},
         new Plaza {Id=601,Nombre="El Cercado"},
         new Plaza {Id=601,Nombre="Villa De Santiago"},
         new Plaza {Id=610,Nombre="Oaxaca"},
         new Plaza {Id=613,Nombre="Tlaxiaco"},
         new Plaza {Id=614,Nombre="Huajuapan De Leon"},
         new Plaza {Id=616,Nombre="Ixtepec"},
         new Plaza {Id=617,Nombre="Juchitan"},
         new Plaza {Id=619,Nombre="Loma Bonita"},
         new Plaza {Id=620,Nombre="Matias Romero"},
         new Plaza {Id=621,Nombre="Miahuatlan"},
         new Plaza {Id=622,Nombre="Ocotlan"},
         new Plaza {Id=624,Nombre="Puerto Escondido"},
         new Plaza {Id=626,Nombre="Salina Cruz"},
         new Plaza {Id=627,Nombre="Lagunas"},
         new Plaza {Id=628,Nombre="Tuxtepec"},
         new Plaza {Id=630,Nombre="Pochutla"},
         new Plaza {Id=631,Nombre="San Pedro Tapanatepec"},
         new Plaza {Id=632,Nombre="Santa Lucia Del Camino, O"},
         new Plaza {Id=634,Nombre="Bahias De Huatulco"},
         new Plaza {Id=635,Nombre="Santiago Juxtlahuaca"},
         new Plaza {Id=636,Nombre="Pinotepa Nacional"},
         new Plaza {Id=637,Nombre="Tehuantepec"},
         new Plaza {Id=638,Nombre="Tlacolula"},
         new Plaza {Id=640,Nombre="Zimatlan"},
         new Plaza {Id=650,Nombre="Cholula"},
         new Plaza {Id=650,Nombre="La Resurreccion"},
         new Plaza {Id=650,Nombre="Puebla"},
         new Plaza {Id=650,Nombre="San Baltazar Campeche"},
         new Plaza {Id=652,Nombre="Acatzingo"},
         new Plaza {Id=654,Nombre="Atlixco"},
         new Plaza {Id=656,Nombre="Cuetzalan"},
         new Plaza {Id=659,Nombre="Huauchinango"},
         new Plaza {Id=662,Nombre="Izucar De Matamoros"},
         new Plaza {Id=667,Nombre="San Martin Texmelucan"},
         new Plaza {Id=668,Nombre="San Felipe Hueyotlipan"},
         new Plaza {Id=669,Nombre="Tecamachalco"},
         new Plaza {Id=670,Nombre="Tehuacan"},
         new Plaza {Id=671,Nombre="San Lorenzo"},
         new Plaza {Id=672,Nombre="Teziutlan"},
         new Plaza {Id=674,Nombre="Xicotepec De Juarez"},
         new Plaza {Id=676,Nombre="Zacatlan"},
         new Plaza {Id=680,Nombre="Pedro Escobedo"},
         new Plaza {Id=680,Nombre="Queretaro"},
         new Plaza {Id=680,Nombre="Villa Corregidora"},
         new Plaza {Id=681,Nombre="Amealco"},
         new Plaza {Id=685,Nombre="San Juan Del Rio"},
         new Plaza {Id=686,Nombre="Tequisquiapan"},
         new Plaza {Id=690,Nombre="Chetumal"},
         new Plaza {Id=691,Nombre="Cancun"},
         new Plaza {Id=691,Nombre="Col. Puerto Juarez"},
         new Plaza {Id=692,Nombre="Cozumel"},
         new Plaza {Id=694,Nombre="Playa Del Carmen"},
         new Plaza {Id=700,Nombre="San Luis Potosi"},
         new Plaza {Id=703,Nombre="Cerritos"},
         new Plaza {Id=705,Nombre="Cuidad Valles"},
         new Plaza {Id=709,Nombre="Matehuala"},
         new Plaza {Id=711,Nombre="Rio Verde"},
         new Plaza {Id=716,Nombre="Tamuin"},
         new Plaza {Id=730,Nombre="Culiacan"},
         new Plaza {Id=735,Nombre="Concordia"},
         new Plaza {Id=736,Nombre="Cosala"},
         new Plaza {Id=737,Nombre="Choix"},
         new Plaza {Id=738,Nombre="El Fuerte"},
         new Plaza {Id=739,Nombre="Escuinapa"},
         new Plaza {Id=740,Nombre="Guamuchil"},
         new Plaza {Id=741,Nombre="Guasave"},
         new Plaza {Id=743,Nombre="Los Mochis"},
         new Plaza {Id=743,Nombre="Topolobampo"},
         new Plaza {Id=744,Nombre="Mazatlan"},
         new Plaza {Id=745,Nombre="Mocorito"},
         new Plaza {Id=746,Nombre="Navolato"},
         new Plaza {Id=760,Nombre="Hermosillo"},
         new Plaza {Id=761,Nombre="Agua Prieta"},
         new Plaza {Id=765,Nombre="Caborca"},
         new Plaza {Id=766,Nombre="Cananea"},
         new Plaza {Id=767,Nombre="Ciudad Obregon"},
         new Plaza {Id=767,Nombre="Esperanza"},
         new Plaza {Id=769,Nombre="Empalme"},
         new Plaza {Id=770,Nombre="Guaymas"},
         new Plaza {Id=770,Nombre="San Carlos"},
         new Plaza {Id=771,Nombre="Huatabampo"},
         new Plaza {Id=773,Nombre="Magdalena"},
         new Plaza {Id=776,Nombre="Nacozari De Garcia"},
         new Plaza {Id=777,Nombre="Navojoa"},
         new Plaza {Id=778,Nombre="Nogales"},
         new Plaza {Id=779,Nombre="Puerto Pe?Asco"},
         new Plaza {Id=780,Nombre="San Luis Rio Colorado"},
         new Plaza {Id=790,Nombre="Tamulte"},
         new Plaza {Id=790,Nombre="Villa Hermosa"},
         new Plaza {Id=792,Nombre="Cardenas"},
         new Plaza {Id=793,Nombre="Ciudad Pemex"},
         new Plaza {Id=794,Nombre="Comalcalco"},
         new Plaza {Id=796,Nombre="Emiliano Zapata"},
         new Plaza {Id=797,Nombre="Frontera"},
         new Plaza {Id=798,Nombre="Huimanguillo"},
         new Plaza {Id=800,Nombre="Jalpa De Mendez"},
         new Plaza {Id=802,Nombre="Macuspana"},
         new Plaza {Id=803,Nombre="Nacajuca"},
         new Plaza {Id=804,Nombre="Paraiso"},
         new Plaza {Id=805,Nombre="Tacotalpa"},
         new Plaza {Id=806,Nombre="Teapa"},
         new Plaza {Id=807,Nombre="Tenosique"},
         new Plaza {Id=810,Nombre="Ciudad Victoria"},
         new Plaza {Id=811,Nombre="Altamira"},
         new Plaza {Id=813,Nombre="Ciudad Madero"},
         new Plaza {Id=813,Nombre="Tampico"},
         new Plaza {Id=814,Nombre="Ciudad Mante"},
         new Plaza {Id=818,Nombre="Matamoros"},
         new Plaza {Id=821,Nombre="Colombia"},
         new Plaza {Id=821,Nombre="Nuevo Laredo"},
         new Plaza {Id=822,Nombre="Reynosa"},
         new Plaza {Id=823,Nombre="Rio Bravo"},
         new Plaza {Id=825,Nombre="Soto La Marina"},
         new Plaza {Id=826,Nombre="Valle Hermoso"},
         new Plaza {Id=830,Nombre="Tlaxcala"},
         new Plaza {Id=832,Nombre="Apizaco"},
         new Plaza {Id=834,Nombre="Santa Ana Chiautempan"},
         new Plaza {Id=840,Nombre="Jalapa"},
         new Plaza {Id=841,Nombre="Acayucan"},
         new Plaza {Id=843,Nombre="Agua Dulce"},
         new Plaza {Id=845,Nombre="Alamo"},
         new Plaza {Id=846,Nombre="Altotonga"},
         new Plaza {Id=848,Nombre="Banderilla"},
         new Plaza {Id=849,Nombre="Boca Del Rio"},
         new Plaza {Id=852,Nombre="Ciudad Mendoza"},
         new Plaza {Id=853,Nombre="Coatepec"},
         new Plaza {Id=854,Nombre="Coatzacoalcos"},
         new Plaza {Id=855,Nombre="Cordoba"},
         new Plaza {Id=856,Nombre="Cosamaloapan"},
         new Plaza {Id=860,Nombre="Cuitlahuac"},
         new Plaza {Id=863,Nombre="Fortin De Las Flores"},
         new Plaza {Id=864,Nombre="Gutierrez Zamora"},
         new Plaza {Id=865,Nombre="Huatusco"},
         new Plaza {Id=867,Nombre="Isla"},
         new Plaza {Id=868,Nombre="Ixtaczoquitlan"},
         new Plaza {Id=869,Nombre="Jaltipan"},
         new Plaza {Id=871,Nombre="Juan Rodriguez Clara"},
         new Plaza {Id=872,Nombre="Villa Jose Cardel"},
         new Plaza {Id=873,Nombre="Las Choapas"},
         new Plaza {Id=875,Nombre="Naranjos"},
         new Plaza {Id=876,Nombre="Martinez De La Torre"},
         new Plaza {Id=877,Nombre="Minatitlan"},
         new Plaza {Id=878,Nombre="Misantla"},
         new Plaza {Id=879,Nombre="Nanchital"},
         new Plaza {Id=882,Nombre="Orizaba"},
         new Plaza {Id=885,Nombre="Papantla"},
         new Plaza {Id=886,Nombre="Perote"},
         new Plaza {Id=888,Nombre="Poza Rica"},
         new Plaza {Id=889,Nombre="Rio Blanco"},
         new Plaza {Id=890,Nombre="San Andres Tuxtla"},
         new Plaza {Id=891,Nombre="San Rafael"},
         new Plaza {Id=894,Nombre="Platon Sanchez"},
         new Plaza {Id=894,Nombre="Tantoyuca"},
         new Plaza {Id=895,Nombre="Tempoal"},
         new Plaza {Id=898,Nombre="Tierra Blanca"},
         new Plaza {Id=901,Nombre="Tlapacoyan"},
         new Plaza {Id=903,Nombre="Tuxpam De Rodriguez Cano"},
         new Plaza {Id=905,Nombre="Cd. Industrial Framboyan"},
         new Plaza {Id=905,Nombre="Veracruz"},
         new Plaza {Id=910,Nombre="Merida"},
         new Plaza {Id=913,Nombre="Motul"},
         new Plaza {Id=914,Nombre="Oxkutzcab"},
         new Plaza {Id=915,Nombre="Progreso"},
         new Plaza {Id=917,Nombre="Ticul"},
         new Plaza {Id=918,Nombre="Tizimin"},
         new Plaza {Id=920,Nombre="Valladolid"},
         new Plaza {Id=930,Nombre="Zacatecas"},
         new Plaza {Id=933,Nombre="Fresnillo"},
         new Plaza {Id=934,Nombre="Guadalupe"},
         new Plaza {Id=935,Nombre="Jalpa"},
         new Plaza {Id=936,Nombre="Jerez De G. Salinas"},
         new Plaza {Id=938,Nombre="Juchipila"},
         new Plaza {Id=939,Nombre="Loreto"},
         new Plaza {Id=946,Nombre="Nochistlan"},
         new Plaza {Id=958,Nombre="Valparaiso"},
         new Plaza {Id=960,Nombre="Calera De V. Rosales"}
     };

            return plazas;
        }
    }
}